### ISSUE TITLE
 agg_renderer_outline_aa.h build error on Ubuntu 20.04

### ISSUE THREAD

**Issue by sangshuduo** [VincentWei/mgplus#1]
OS: Ubuntu 20.04
branch: master

reproduce steps:
$ ./autogen.sh
$ ./configure
$ make

Output:
...

g++ -DHAVE_CONFIG_H -I. -I../.. -D__MGPLUS_LIB__ -DNDEBUG -I/usr/include/freetype2 -I/usr/include/libpng16 -g -O2 -MT agg_trans_warp_magnifier.lo -MD -MP -MF .deps/agg_trans_warp_magnifier.Tpo -c agg_trans_warp_magnifier.cpp -o agg_trans_warp_magnifier.o >/dev/null 2>&1
mv -f .libs/agg_trans_warp_magnifier.lo agg_trans_warp_magnifier.lo
depbase=`echo agg_vpgen_clip_polygon.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ../../libtool    --mode=compile g++ -DHAVE_CONFIG_H -I. -I../..  -D__MGPLUS_LIB__ -DNDEBUG -I/usr/include/freetype2 -I/usr/include/libpng16  -g -O2 -MT agg_vpgen_clip_polygon.lo -MD -MP -MF $depbase.Tpo -c -o agg_vpgen_clip_polygon.lo agg_vpgen_clip_polygon.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
rm -f .libs/agg_vpgen_clip_polygon.lo
g++ -DHAVE_CONFIG_H -I. -I../.. -D__MGPLUS_LIB__ -DNDEBUG -I/usr/include/freetype2 -I/usr/include/libpng16 -g -O2 -MT agg_vpgen_clip_polygon.lo -MD -MP -MF .deps/agg_vpgen_clip_polygon.Tpo -c agg_vpgen_clip_polygon.cpp  -fPIC -DPIC -o .libs/agg_vpgen_clip_polygon.lo
g++ -DHAVE_CONFIG_H -I. -I../.. -D__MGPLUS_LIB__ -DNDEBUG -I/usr/include/freetype2 -I/usr/include/libpng16 -g -O2 -MT agg_vpgen_clip_polygon.lo -MD -MP -MF .deps/agg_vpgen_clip_polygon.Tpo -c agg_vpgen_clip_polygon.cpp -o agg_vpgen_clip_polygon.o >/dev/null 2>&1
mv -f .libs/agg_vpgen_clip_polygon.lo agg_vpgen_clip_polygon.lo
depbase=`echo agg_bezier_arc.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ../../libtool    --mode=compile g++ -DHAVE_CONFIG_H -I. -I../..  -D__MGPLUS_LIB__ -DNDEBUG -I/usr/include/freetype2 -I/usr/include/libpng16  -g -O2 -MT agg_bezier_arc.lo -MD -MP -MF $depbase.Tpo -c -o agg_bezier_arc.lo agg_bezier_arc.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
rm -f .libs/agg_bezier_arc.lo
g++ -DHAVE_CONFIG_H -I. -I../.. -D__MGPLUS_LIB__ -DNDEBUG -I/usr/include/freetype2 -I/usr/include/libpng16 -g -O2 -MT agg_bezier_arc.lo -MD -MP -MF .deps/agg_bezier_arc.Tpo -c agg_bezier_arc.cpp  -fPIC -DPIC -o .libs/agg_bezier_arc.lo
g++ -DHAVE_CONFIG_H -I. -I../.. -D__MGPLUS_LIB__ -DNDEBUG -I/usr/include/freetype2 -I/usr/include/libpng16 -g -O2 -MT agg_bezier_arc.lo -MD -MP -MF .deps/agg_bezier_arc.Tpo -c agg_bezier_arc.cpp -o agg_bezier_arc.o >/dev/null 2>&1
mv -f .libs/agg_bezier_arc.lo agg_bezier_arc.lo
depbase=`echo agg_line_profile_aa.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ../../libtool    --mode=compile g++ -DHAVE_CONFIG_H -I. -I../..  -D__MGPLUS_LIB__ -DNDEBUG -I/usr/include/freetype2 -I/usr/include/libpng16  -g -O2 -MT agg_line_profile_aa.lo -MD -MP -MF $depbase.Tpo -c -o agg_line_profile_aa.lo agg_line_profile_aa.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
rm -f .libs/agg_line_profile_aa.lo
g++ -DHAVE_CONFIG_H -I. -I../.. -D__MGPLUS_LIB__ -DNDEBUG -I/usr/include/freetype2 -I/usr/include/libpng16 -g -O2 -MT agg_line_profile_aa.lo -MD -MP -MF .deps/agg_line_profile_aa.Tpo -c agg_line_profile_aa.cpp  -fPIC -DPIC -o .libs/agg_line_profile_aa.lo
In file included from agg_line_profile_aa.cpp:37:
agg_renderer_outline_aa.h: In member function 'agg::line_profile_aa& agg::renderer_outline_aa<BaseRenderer>::profile()':
agg_renderer_outline_aa.h:1390:45: error: binding reference of type 'agg::line_profile_aa&' to 'const agg::line_profile_aa' discards qualifiers
 1390 |         line_profile_aa& profile() { return *m_profile; }
      |                                             ^~~~~~~~~~
make[4]: *** [Makefile:654: agg_line_profile_aa.lo] Error 1
make[4]: Leaving directory '/home/shuduo/work/minigui/mgplus/src/agg'
make[3]: *** [Makefile:675: all-recursive] Error 1
make[3]: Leaving directory '/home/shuduo/work/minigui/mgplus/src/agg'
make[2]: *** [Makefile:476: all-recursive] Error 1
make[2]: Leaving directory '/home/shuduo/work/minigui/mgplus/src'
make[1]: *** [Makefile:491: all-recursive] Error 1
make[1]: Leaving directory '/home/shuduo/work/minigui/mgplus'
make: *** [Makefile:379: all] Error 2

**Comment by VincentWei** [comment]
Thanks for your information. Would you like to set your C++ compiler complies with C++11 or C++14? It is ok for me when I use Ubuntu 18.0.4, GCC 7.4.0.

**Comment by sangshuduo** [comment]
Yes. it works on 18.04
